---

- name: Clear Clang symlink
  file: path={{ CLANG_SYMLINK }} state=absent

- name: Install Clang and Go
  command: "{{ item }}"
  with_items:
    - bash -c "curl -fsSL https://raw.githubusercontent.com/cilium/cilium/master/contrib/packer-scripts/ubuntu-14.04/scripts/go.sh | sh"
  ignore_errors: yes
